Calling tool with arguments:

raised the following error:

<class 'TypeError'>: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'list'>